name: Build and push Docker image
on:
  push:
    # Start build on main branch push
    branches:
    - main
    # Ignore changes to deployment manifests
    paths-ignore:
    - deploy/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   
  USERNAME: ${{ github.actor }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Login to Docker Hub
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # Get the current date and time - we will use this as a tag for the image later
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"  
    - name: Build and push
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
      with:
        context: ./code
        file: ./Dockerfile
        push: true
        tags: >
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}, 
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          